---
- hosts: all
  become: yes
  tasks:
 
  - name: Add user to remote hosts
    user: name=admin groups=sudo shell=/bin/bash password=$6$KjyfytoJ$hoQdVIGcRZgje2HpHFf8ldvooLfY774SrEpHkADUf3d7uGBSwVLeMXsPIfb4l2TaXWvprMz868ZbH8HLaiDeh.
 
  - name: Add SSH keys to remote hosts
    authorized_key: user=admin key="{{ lookup('file', "/home/admin/Downloads/key.pub") }}"
