- hosts: appservers-nginx
  sudo: yes

  - name: Install Nginx Web Server on Debian Family
  apt:
    name=nginx
    state=latest
  when:
    ansible_os_family == "Debian"
	
  roles:
  - { role: users }
  - { role: http }
  
  notify:
    - nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: started